// GENERATED by scripts/gen-height.mjs from src/shaders/terrain.glsl -- DO NOT EDIT.
// The GLSL is the single source of truth; re-run `node scripts/gen-height.mjs` after editing
// the terrain HEIGHT functions. `g` = the GLSL runtime shim (glsl-rt.js); `U` = uniform values;
// hpfSample is supplied by the caller (the pure-JS anchor-field) via the U/ctx closure.
import * as g from './glsl-rt.js';

export function makeHeight(U, hpfSample) {
  const C_LAKE_CARVE_DEPTH = 220.0;
  const C_OCT_ROT = g.mat3(0.80, 0.36, -0.48, -0.48, 0.86, -0.18, 0.36, 0.36, 0.86);
  const C_RIVER_INCISE_DEPTH = 280.0;
  const C_CANYON_INCISE_DEPTH = 700.0;
  const C_MESA_HEIGHT = 650.0;
  const C_DUNE_AMP = 120.0;
  function shash3(p) {
    p = g.fract(g.add(g.mul(p, 0.3183099), g.vec3(0.1, 0.2, 0.3)));
    p = g.add(p, g.dot(p, g.add(g.sw(p, 'yzx'), 19.19)));
    return g.fract((((g.sw(p, 'x') + g.sw(p, 'y')) * g.sw(p, 'z')) + ((g.sw(p, 'y') + g.sw(p, 'z')) * g.sw(p, 'x'))));
  }

  function snoise3(P) {
    let i = g.floor(P);
    let f = g.fract(P);
    let u = g.mul(g.mul(f, f), g.sub(3.0, g.mul(2.0, f)));
    let n000 = shash3(i);
    let n100 = shash3(g.add(i, g.vec3(1, 0, 0)));
    let n010 = shash3(g.add(i, g.vec3(0, 1, 0)));
    let n110 = shash3(g.add(i, g.vec3(1, 1, 0)));
    let n001 = shash3(g.add(i, g.vec3(0, 0, 1)));
    let n101 = shash3(g.add(i, g.vec3(1, 0, 1)));
    let n011 = shash3(g.add(i, g.vec3(0, 1, 1)));
    let n111 = shash3(g.add(i, g.vec3(1, 1, 1)));
    let x00 = g.mix(n000, n100, g.sw(u, 'x'));
    let x10 = g.mix(n010, n110, g.sw(u, 'x'));
    let x01 = g.mix(n001, n101, g.sw(u, 'x'));
    let x11 = g.mix(n011, n111, g.sw(u, 'x'));
    return ((g.mix(g.mix(x00, x10, g.sw(u, 'y')), g.mix(x01, x11, g.sw(u, 'y')), g.sw(u, 'z')) * 2.0) - 1.0);
  }

  function inciseRidgeField(d, baseFreq, freqMul) {
    let p = d;
    let freq = baseFreq;
    let amp = 1.0;
    let sum = 0.0;
    let norm = 0.0;
    let irOcts = ((U.uInciseRidgeOcts > 0) ? U.uInciseRidgeOcts : 4);
    for (let o = 0; (o < irOcts); o++) {
      sum += (amp * (1.0 - g.abs(snoise3(g.mul(p, freq)))));
      norm += amp;
      freq *= freqMul;
      amp *= 0.5;
      p = g.mat3mul(C_OCT_ROT, p);
    }
    return (sum / norm);
  }

  function lakeBasinField(dir) {
    return (0.5 + (0.5 * snoise3(g.add(g.mul(dir, 55.0), g.vec3(4.0, 9.0, 1.0)))));
  }

  function lakeCarveM(dir) {
    let wet = 0;
    let basin = lakeBasinField(dir);
    let shoulder = g.smoothstep(0.30, 0.74, basin);
    let bowl = g.smoothstep(0.50, 0.80, basin);
    wet = g.smoothstep(0.50, 0.70, basin);
    return [((-C_LAKE_CARVE_DEPTH) * ((0.65 * shoulder) + (0.35 * bowl))), wet];
  }

  function riverRidgeField(dir) {
    return inciseRidgeField(dir, 96.0, 2.03);
  }

  function riverCarveM(dir) {
    let wet = 0;
    let ridge = riverRidgeField(dir);
    let valley = g.smoothstep(0.55, 0.92, ridge);
    let thalweg = g.smoothstep(0.74, 0.96, ridge);
    wet = g.smoothstep(0.80, 0.95, ridge);
    return [((-C_RIVER_INCISE_DEPTH) * ((0.7 * valley) + (0.3 * thalweg))), wet];
  }

  function canyonRidgeField(dir) {
    return inciseRidgeField(g.add(dir, g.vec3(13.7, (-4.2), 8.9)), 90.0, 2.07);
  }

  function canyonCarveM(dir) {
    let depth = 0;
    let ridge = canyonRidgeField(dir);
    let wall = g.smoothstep(0.52, 0.84, ridge);
    let floorF = g.smoothstep(0.66, 0.93, ridge);
    depth = g.max(wall, floorF);
    let profile = g.max(wall, floorF);
    let dmul = ((U.canyonDepthMul > 0.0) ? U.canyonDepthMul : 1.0);
    let carve = (((-C_CANYON_INCISE_DEPTH) * dmul) * profile);
    let dn = dir;
    let g1 = inciseRidgeField(g.add(dn, g.vec3(5.1, 8.3, (-2.7))), 219.0, 2.11);
    let g2 = inciseRidgeField(g.add(dn, g.vec3((-7.4), 1.9, 6.2)), 875.0, 2.05);
    let g3 = inciseRidgeField(g.add(dn, g.vec3(2.2, (-4.1), 8.8)), 1750.0, 2.02);
    carve += ((-55.0) * g.smoothstep(0.50, 0.92, g1));
    carve += ((-28.0) * g.smoothstep(0.55, 0.93, g2));
    carve += ((-14.0) * g.smoothstep(0.58, 0.94, g3));
    return [carve, depth];
  }

  function badlandsRegion(d) {
    let r = snoise3(g.add(g.mul(d, 11.0), g.vec3(31.7, (-12.3), 5.1)));
    return g.smoothstep(0.30, 0.55, r);
  }

  function mesaField(d) {
    let w = d;
    w[undefined] = g.add(w[undefined], g.mul(0.10, g.vec2(snoise3(g.add(g.mul(d, 40.0), 5.0)), snoise3(g.add(g.mul(d, 40.0), 11.0)))));
    let a = snoise3(g.add(g.mul(w, 55.0), g.vec3(3.1, 7.7, 1.3)));
    let b = snoise3(g.add(g.mul(w, 130.0), g.vec3(9.4, 2.2, 6.6)));
    return (0.5 + (0.5 * ((0.7 * a) + (0.3 * b))));
  }

  function broadShapeLowM(dir) {
    if ((U.hasHpf == 0)) {
      return 0.0;
    }
    let d = g.normalize(dir);
    let amp = 6500.0;
    let freq = 0.75;
    let sum = 0.0;
    let blOcts = ((U.uBroadLowOcts > 0) ? U.uBroadLowOcts : 8);
    for (let o = 0; (o < blOcts); o++) {
      sum += (amp * snoise3(g.mul(d, freq)));
      amp *= ((o < 6) ? 0.66 : 0.82);
      freq *= 2.0;
    }
    return (sum - 500.0);
  }

  function cliffTerraceM(dir, h) {
    let cliffOut = 0;
    cliffOut = 0.0;
    if ((h <= 0.0)) {
      return [0.0, cliffOut];
    }
    let d = g.normalize(dir);
    let region = badlandsRegion(d);
    if ((region <= 0.0)) {
      return [0.0, cliffOut];
    }
    let e = 2400.0;
    let ux = g.normalize(g.cross(((g.abs(g.sw(d, 'y')) < 0.99) ? g.vec3(0.0, 1.0, 0.0) : g.vec3(1.0, 0.0, 0.0)), d));
    let h0 = broadShapeLowM(d);
    let gx = ((broadShapeLowM(g.normalize(g.add(d, g.mul(ux, (e / U.defRadius))))) - h0) / e);
    let flatness = (1.0 - g.smoothstep(0.05, 0.16, g.abs(gx)));
    let gate = (region * flatness);
    if ((gate <= 0.0)) {
      return [0.0, cliffOut];
    }
    let m = mesaField(d);
    let THR = 0.56;
    let TH = 0.24;
    let top = g.smoothstep((THR - TH), (THR + TH), m);
    let butte = g.smoothstep((0.74 - TH), (0.74 + TH), m);
    let rise = (((0.7 * top) + (0.3 * butte)) * C_MESA_HEIGHT);
    let rim = (g.max((top * (1.0 - top)), (butte * (1.0 - butte))) * 4.0);
    cliffOut = (g.clamp(rim, 0.0, 1.0) * gate);
    let camt = ((U.cliffAmt > 0.0) ? U.cliffAmt : 1.0);
    return [((rise * camt) * gate), cliffOut];
  }

  function duneFieldM(dir) {
    let crest = 0;
    let d = g.normalize(dir);
    let big = ((snoise3(g.add(g.mul(d, 2000.0), g.vec3(2.0, 7.0, 5.0))) * 0.5) + 0.5);
    let dune = g.pow(big, 1.6);
    let med = ((snoise3(g.mul(d, 6000.0)) * 0.5) + 0.5);
    crest = g.smoothstep(0.55, 0.92, big);
    return [((C_DUNE_AMP * dune) + (40.0 * (med * dune))), crest];
  }

  function ruggedFromElevAmp(elevAmp) {
    return g.mix(0.5, 1.8, g.smoothstep(15.0, 18.6, elevAmp));
  }

  function faceWarp(p) {
    return g.mul(U.defRadius, g.tan(g.mul(g.div(p, U.defRadius), 0.7853981634)));
  }

  function broadShapeM(dir, reliefMul, ridgeMul) {
    if ((U.hasHpf == 0)) {
      return 0.0;
    }
    let mtnAmp = 1.0;
    let d = g.normalize(dir);
    let amp = 6500.0;
    let freq = 0.75;
    let sum = 0.0;
    let octMax = ((U.uOctMax > 0) ? U.uOctMax : 12);
    for (let o = 0; (o < octMax); o++) {
      let sf = ((o >= 6) ? (freq * 0.667) : freq);
      let nn = snoise3(g.mul(d, sf));
      if ((o >= 6)) {
        let r = (((1.0 - g.abs(nn)) * 2.0) - 1.0);
        nn = g.mix(nn, r, (ridgeMul * 0.8));
        nn *= reliefMul;
        nn *= 1.36;
        nn *= U.uHiFreqCut;
      }
      sum += (amp * nn);
      amp *= ((o < 6) ? 0.66 : 0.80);
      freq *= 2.0;
    }
    let hi = g.max((sum - 500.0), 0.0);
    let peak = g.smoothstep(1200.0, 5000.0, hi);
    let liftK = (0.06 + (0.16 * g.clamp(reliefMul, 0.0, 1.7)));
    sum += ((hi * peak) * liftK);
    let belt = g.clamp(((reliefMul - 0.45) / 1.25), 0.0, 1.0);
    if (((belt > 0.0) && (hi > 0.0))) {
      let e0 = ((snoise3(g.add(g.mul(d, 2.0), g.vec3(11.0, 3.0, 7.0))) * 0.5) + 0.5);
      let e1 = ((snoise3(g.add(g.mul(d, 3.5), g.vec3(2.0, 9.0, 4.0))) * 0.5) + 0.5);
      let modu = (0.7 + (0.3 * g.clamp(((e0 * 0.7) + (e1 * 0.3)), 0.0, 1.0)));
      let landGate = g.smoothstep(0.0, 800.0, hi);
      let base = ((belt * landGate) * modu);
      sum += ((base * 5200.0) * mtnAmp);
      if ((base > 0.01)) {
        let pf = 50.0;
        let pa = 1.0;
        let ps = 0.0;
        let pn = 0.0;
        let pkOcts = ((U.uPeakOcts > 0) ? U.uPeakOcts : 3);
        for (let o = 0; (o < pkOcts); o++) {
          ps += (pa * (1.0 - g.abs(snoise3(g.add(g.mul(d, pf), g.vec3(3.3, 7.7, 1.1))))));
          pn += pa;
          pa *= 0.65;
          pf *= 2.13;
        }
        let crest = (ps / pn);
        sum += (((base * g.pow(crest, 4.5)) * 8400.0) * mtnAmp);
      }
    }
    {
      let e = (sum - 500.0);
      e *= 0.85;
      let CK = 6500.0;
      let CMAX = 42000.0;
      if ((e > CK)) {
        let x = (e - CK);
        e = (CK + ((CMAX - CK) * g.tanh((x / 26000.0))));
      }
      return e;
    }
  }

  function vtxDisplace(fp, tileM, rugged) {
    return 0.0;
  }

  function detailFbm(dir) {
    let ov = 0.0;
    let oa = 0.0;
    let fq = 75.0;
    let am = 1.0;
    let dfOcts = ((U.uDetailFbmOcts > 0) ? U.uDetailFbmOcts : 3);
    for (let o = 0; (o < dfOcts); o++) {
      ov += (am * snoise3(g.add(g.mul(dir, fq), g.vec3((g.float(o) * 7.3)))));
      oa += am;
      fq *= 5.0;
      am *= 0.75;
    }
    return (ov / oa);
  }

  function computeHCache(dir0) {
    let hpf0 = hpfSample(dir0);
    let cbias = g.sw(hpf0, 'r');
    let rugged = ruggedFromElevAmp(g.sw(hpf0, 'g'));
    let bTemp = g.sw(hpf0, 'b');
    let bHum = g.sw(hpf0, 'a');
    let bAmp = g.sw(hpf0, 'g');
    let mtn = g.smoothstep(g.mix(16.8, 14.5, U.uMtnBandWide), g.mix(18.6, 19.5, U.uMtnBandWide), bAmp);
    let wetLowFlat = (g.smoothstep(g.mix(0.66, 0.50, U.uClimateRelief), g.mix(0.9, 1.0, U.uClimateRelief), bHum) * (1.0 - mtn));
    let coldFlat = (1.0 - g.smoothstep(g.mix(0.18, 0.05, U.uClimateRelief), g.mix(0.34, 0.45, U.uClimateRelief), bTemp));
    let reliefMul = g.clamp((((0.45 + (1.25 * mtn)) - (0.30 * wetLowFlat)) - (0.25 * coldFlat)), 0.40, 1.7);
    let ridgeMul = g.clamp((mtn * 1.1), 0.0, 1.0);
    let isleZone = (g.smoothstep(g.mix(50.0, 30.0, U.uIsleWide), g.mix(350.0, 600.0, U.uIsleWide), cbias) * (1.0 - g.smoothstep(g.mix(900.0, 600.0, U.uIsleWide), g.mix(1600.0, 2200.0, U.uIsleWide), cbias)));
    if ((isleZone > 0.0)) {
      let isleType = snoise3(g.mul(dir0, 9.0));
      let volcanic = g.smoothstep(0.25, 0.7, isleType);
      let atoll = g.smoothstep(0.25, 0.7, (-isleType));
      reliefMul = g.mix(reliefMul, (g.mix(reliefMul, 1.6, volcanic) * (1.0 - (0.7 * atoll))), isleZone);
      ridgeMul = g.mix(ridgeMul, g.max(ridgeMul, (0.9 * volcanic)), isleZone);
    }
    return { hpf0: hpf0, rugged: rugged, reliefMul: reliefMul, ridgeMul: ridgeMul };
  }

  function composeHeightC(dir0, faceLocal, tileM, _C, skipCarves) {
    let hpf0 = _C.hpf0;
    let cbias = g.sw(hpf0, 'r');
    let rugged = _C.rugged;
    let vDisp = vtxDisplace(faceLocal, tileM, rugged);
    let reliefMul = _C.reliefMul;
    let ridgeMul = _C.ridgeMul;
    let bShape = broadShapeM(dir0, reliefMul, ridgeMul);
    let h = ((cbias + bShape) + U.uLandBias);
    if ((h < 0.0)) {
      let COAST_RING_CEIL = 500.0;
      h = g.min(h, (cbias + COAST_RING_CEIL));
      let SEABED_EASE = 25.0;
      let d0 = (-h);
      let d = ((d0 < SEABED_EASE) ? (((d0 * d0) / SEABED_EASE) * (2.0 - (d0 / SEABED_EASE))) : d0);
      h = (-((g.min(d, 70.0) * 0.45) + (g.max((d - 70.0), 0.0) * 0.85)));
      h = g.max(h, (-11000.0));
    }
    else {
      let bShelf = ((U.uBeachShelfM > 1.0) ? U.uBeachShelfM : 600.0);
      if ((h < bShelf)) {
        h = (((h * h) / bShelf) * (2.0 - (h / bShelf)));
      }
      if (h > 0.0) {
        const curve = (U.uHeightCurve > 0.0) ? U.uHeightCurve : 1.0;
        const REF = 8000.0;
        h = Math.pow(Math.min(h / REF, 1.0), curve) * REF;
      }
    }
    h += (vDisp * g.mix(1.0, 2.2, g.clamp(((h + 50.0) / (-550.0)), 0.0, 1.0)));
    h += (((detailFbm(dir0) * U.uDetailOverlay) * 30.0) * g.step(0.0, h));
    if ((U.uVsCheap > 0.5)) {
      return h;
    }
    if (skipCarves) {
      return h;
    }
    let flatGate = g.max(0.0, (1.0 - (reliefMul * 2.0)));
    let valleyV = (1.0 - inciseRidgeField(dir0, 31.0, 2.0));
    let valleyVal = (((g.smoothstep(0.25, 0.80, valleyV) * flatGate) * U.uDetailOverlay) * 24.0);
    h -= valleyVal;
    let lakeWetV = 0;
    let lakeCarveRaw = lakeCarveM(dir0)[0];
    let lakeGateLo = (g.mix(0.60, 0.50, U.uCarveWide) - (0.12 * flatGate));
    let lakeGate = (g.smoothstep(lakeGateLo, g.mix(0.85, 0.95, U.uCarveWide), g.sw(hpf0, 'a')) * g.step(0.0, h));
    let lakeCarveV = (lakeCarveRaw * lakeGate);
    h += lakeCarveV;
    let lakeWet = (lakeWetV * lakeGate);
    if ((lakeWet > 0.0)) {
      let waterLevel = (g.max(h, 0.0) - 25.0);
      h = g.mix(h, waterLevel, lakeWet);
      vDisp *= (1.0 - lakeWet);
    }
    let riverWet = (g.smoothstep(g.mix(0.30, 0.20, U.uCarveWide), g.mix(0.55, 0.65, U.uCarveWide), g.sw(hpf0, 'a')) * g.smoothstep(g.mix(0.20, 0.12, U.uCarveWide), g.mix(0.34, 0.46, U.uCarveWide), g.sw(hpf0, 'b')));
    let riverWetMask = 0;
    let riverCarveV = ((riverCarveM(dir0)[0] * riverWet) * g.step(0.0, h));
    let canyonDepMask = 0;
    let canyonCarveV = (canyonCarveM(dir0)[0] * g.smoothstep(0.0, 250.0, h));
    let inciseTot = (riverCarveV + canyonCarveV);
    if ((h > 5.0)) {
      h = g.max((h + inciseTot), g.max(5.0, (h - (450.0 * ((U.canyonDepthMul > 0.0) ? U.canyonDepthMul : 1.0)))));
    }
    let cliffFaceMask = 0;
    let cliffCarveV = (cliffTerraceM(dir0, h)[0] * g.step(0.0, h));
    h += cliffCarveV;
    let riverWetLine = ((riverWetMask * riverWet) * g.step(0.0, h));
    if ((riverWetLine > 0.0)) {
      let rw = g.pow(riverWetLine, 0.6);
      let rWaterLevel = (h - 70.0);
      h = g.mix(h, rWaterLevel, rw);
      vDisp *= (1.0 - rw);
    }
    let duneSand = ((g.smoothstep(g.mix(0.62, 0.50, U.uCarveWide), g.mix(0.85, 0.95, U.uCarveWide), (1.0 - g.sw(hpf0, 'a'))) * g.smoothstep(g.mix(0.40, 0.30, U.uCarveWide), g.mix(0.58, 0.68, U.uCarveWide), g.sw(hpf0, 'b'))) * (1.0 - g.smoothstep(40.0, 160.0, h)));
    let duneCrest = 0;
    let duneV = ((duneFieldM(dir0)[0] * duneSand) * g.step(0.0, h));
    h += duneV;
    return h;
  }

  return { snoise3, broadShapeM, computeHCache, composeHeightC, detailFbm };
}
